name: osim_env
channels:
  - opensim-org
  - conda-forge
  - defaults
dependencies:
  - python=3.12.11
  - opensim=4.5.2
  - numpy=2.0.1
  - gymnasium==1.2.1
  - pip=25.2
  - pip:
      - --index-url https://download.pytorch.org/whl/cu129
      - mlflow==3.4.0
      - torch==2.8.0+cu129
      - torchvision==0.23.0+cu129
